### ISSUE TITLE
Feeds don't populate on iTunes desktop (Windows); fine on mobile

### ISSUE THREAD

**Issue by jordantgh** [madiele/vod2pod-rss#145]
app version: 1.1.0

- [x ] twitch api key set
- [x ] youtube api key set

______
issue description:

Logs do not seem informative. All of the podcasts are *visible* in iTunes, but the feeds are empty. When I select "Refresh Podcast" in the iTunes menu for each feed, nothing changes on the UI, but I get logs like this:

```
vod2pod-rss-vod2pod-1  | 2024-01-26T16:36:45.738Z DEBUG [vod2pod_rss::provider] using TwitchProvider
vod2pod-rss-vod2pod-1  | 2024-01-26T16:36:45.741Z INFO  [vod2pod_rss::server] serving cached rss feed for https://www.twitch.tv/thejrm_
vod2pod-rss-vod2pod-1  | 2024-01-26T16:37:31.593Z DEBUG [vod2pod_rss::provider] using TwitchProvider
vod2pod-rss-vod2pod-1  | 2024-01-26T16:37:31.595Z INFO  [vod2pod_rss::server] serving cached rss feed for https://www.twitch.tv/ev3ntic
```

**Comment by madiele** [comment]
Hi! 
Can you upload the generated feed here by pasting the url in the browser and doing a "save as"?
(be sure to obscure any public url to your server)

Also to have better logs set DEBUG as the value of the RUST_LOG variable in your docker compose, then write them here

**Comment by jordantgh** [comment]
Hey @madiele sorry for the delay: https://gist.github.com/jordantgh/7a19a1974b0e23256db81d829593ed32

**Comment by madiele** [comment]
Thanks, seems like the feed is generated without issues, I smell this is iTunes being picky with something in it.

Since I don't have a mac I don't know if I can test this, I hope the windows version of iTunes is similar enough...

I don't know when I will be able to work on it, in the meanwhile I'll put an help wanted tag on it, if any one with a mac wants to help trying to find the issue.

I imagine the reason is that iTunes requires some field that is currently missing from the rss

**Comment by jordantgh** [comment]
FWIW I experience this issue on the Windows version of iTunes anyway. Don't know whether it would work on macOS.

**Comment by madiele** [comment]
Wait, could it be that you are serving the podcast via http instead https? Many client are very picky about it

**Comment by jordantgh** [comment]
Ah, no, my website at least is https - it seems to be reflected in the generated RSS:

```
...
<enclosure
        url="https://myobscuredomain.co.uk/vod2pod/transcode_media/to_mp3?bitrate=192&amp;uuid=a0cf8e9f-dc61-4d36-8eac-8c6f68f9244c&amp;duration=17051&amp;url=https%3A%2F%2Fwww.twitch.tv%2Fvideos%2F2043179841&amp;ext=.mp3"
        length="3352363008" type="audio/mpeg" />
...
```

**Comment by madiele** [comment]
That's right, I had other people mention pocket cast not accepting the rss and in those cases it was alway them serving it via http or inside their local network, but your case seems different

**Comment by jordantgh** [comment]
These are some observations from ChatGPT after pasting in the feed:

```
Upon reviewing your feed against the provided Apple Podcast Feed Guidelines, there are a few potential issues and missing elements that could be problematic:

1. Language Tag:
   - Your feed is missing the `<language>` tag within the `<channel>` block. Apple Podcasts uses this tag to categorize podcasts based on language, which is important for discoverability.

2. Copyright:
   - You seem to be missing a `<copyright>` tag within the `<channel>` block. This tag communicates the copyright information of your podcast's content.

3. iTunes Tags:
   - Missing `<itunes:explicit>` tag at the channel level: If any episodes contain explicit material, you are required to add this tag at both the channel level and the individual `<item>` levels. You should add `<itunes:explicit>false</itunes:explicit>` (or true, if applicable) under the `<channel>` section.
   - Missing `<itunes:subtitle>` and `<itunes:summary>` tags at the channel level: These tags are important for the Apple Podcasts directory, providing a short and long description, respectively. They should give new listeners a clear idea about what your podcast offers.
   - Missing `<itunes:type>` tag: This tag indicates if the podcast is episodic or serial. It's a newer tag that isn't accounted for in your provided documentation but should be considered for improving feed.

4. Item-Level Issues:
   - `<itunes:summary>` for each item (episode) should provide a clear and concise description of that episode's content. Make sure it is accurate and matches the actual content of the episodes. The CDATA description may suffice, but it is good practice to also fill out the `<itunes:summary>` tag with plain text.
   - `<itunes:duration>` values must be in the format of HH:MM:SS or MM:SS (for hours, minutes, seconds).

5. Enclosure length:
   - The `length` attribute of the `<enclosure>` tag does not seem to correctly represent the file size in bytes (as stated in the guidelines), which could be an issue. Verify these values to ensure they are accurate.

Please address these points, and always refer to the most current Apple Podcasts documentation, as standards and practices may have evolved since the provided guidelines.
```

I am not sure what is seeing to be wrong with the `length` attribute tbh, but otherwise I'd have thought most of these are optional :shrug

**Comment by madiele** [comment]
should be fixed in the beta image

in your compose change latest to beta and see if the episode show up now

the problem was with the way I was generating the url, since they were not ending in .mp3 itunes would not recognize them.

I hope this fix does not break other clients 🤞 

I'll close the issue but let me know if you notice something weird, I want to make sure this change does not break other stuff before the next release

**Comment by jordantgh** [comment]
Not only fixed on iTunes, but also Pocket Casts. Wow, well done! 🥳
