### ISSUE TITLE
At https://y2pod.com submit a YouTube url, response 409 error.

### ISSUE THREAD

**Issue by lainding** [madiele/vod2pod-rss#162]
issue description:

I submit a Youtube url at https://y2pod.com, it responses 409 error and no messages.

![image](https://github.com/madiele/vod2pod-rss/assets/5516006/8a63bfa0-2d62-4505-81e4-db85c112bfbf)

**Comment by madiele** [comment]
I'm not affiliated Y2Pod.com, I do not know who is behind that website, so I can only help you based on your input, if it's on their end I can not help you...

can you please share the link you used for the generation? I will try it in my private instance

**Comment by madiele** [comment]
@lainding I will be closing the issue for inactivity in the following days, if you still have the issue let me know
