### ISSUE TITLE
Would you consider add option to convert to video podcast?

### ISSUE THREAD

**Issue by kennywhat** [madiele/vod2pod-rss#167]
app version: X.X.X

- [ ] twitch api key set
- [ ] youtube api key set

______
issue description:

<your issue here be sure to include logs if you can>

**Comment by madiele** [comment]
Hi, I did some mildly successful experimentation in the past trying to output an mp4 (the git branch is still there if someone is curious), it worked but with too many caveats and I ultimately dropped the idea to focus on other stuff, it's definitely possible but it's something that I would not use personally so it's though for me to justify putting in the work to make it and then maintain it.

So, for now it's a no, but if someone comes along wanting to take the challenge and open a PR and contribute the feature I'm open to accept it, feel free to get in touch by opening an issue and I'll help in the process.
