### ISSUE TITLE
Docker not start with your image

### ISSUE THREAD

**Issue by davnozdu** [madiele/vod2pod-rss#171]
I am try to run your Docker image via Portainer and get this error.
I am try several time, change network setting and other and try to search in Google same problem but not found resolve.
Host system in my NAS x86 platform. linux x86_64 QTS 5.2.0 (20240417)

Error message 
_________________________
2024-05-12T07:23:46.449Z INFO  [app] app version 1.2.1
thread 'main' panicked at src/main.rs:22:9:
Error interacting with Redis (redis is required): Connection refused (os error 111)
:
    /tmp/vod2pod/src/lib.rs:13:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-05-12T07:23:51.338Z INFO  [app] app version 1.2.1
thread 'main' panicked at src/main.rs:22:9:
Error interacting with Redis (redis is required): Connection refused (os error 111)
:
    /tmp/vod2pod/src/lib.rs:13:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by madiele** [comment]
You are missing the redis container, you need to setup portainer to also launch that as it's needed for vod2pod to work.

Either try to import the docker-compose.yml into portainer (I don't use it so I don't know if it can be done, or manually deploy a redis container and change the environment variable for vod2pod to connect to it

**Comment by davnozdu** [comment]
I install redis container.
Then import yml file to portainer but container not create automatically. 
Maybe this system not support x86 processor ?

<img width="1388" alt="Снимок экрана 2024-05-12 в 10 26 52" src="https://github.com/madiele/vod2pod-rss/assets/92220901/f2dc5a97-a2b0-4027-983e-f5e1ae3d1cdd">
<img width="1400" alt="Снимок экрана 2024-05-12 в 10 27 14" src="https://github.com/madiele/vod2pod-rss/assets/92220901/58399e77-1aa7-4370-be6c-bd51e9ac2389">

**Comment by madiele** [comment]
Can you enter the stack?

**Comment by madiele** [comment]
Also have you actually started the stack?

**Comment by davnozdu** [comment]
<img width="1430" alt="Снимок экрана 2024-05-12 в 10 36 13" src="https://github.com/madiele/vod2pod-rss/assets/92220901/55c3a00a-7949-4441-a993-44bb010f8fca">
<img width="1397" alt="Снимок экрана 2024-05-12 в 10 36 01" src="https://github.com/madiele/vod2pod-rss/assets/92220901/9d15bd6d-53c2-4e7a-aa80-28c75c7ab511">

**Comment by davnozdu** [comment]
<img width="1396" alt="Снимок экрана 2024-05-12 в 10 35 48" src="https://github.com/madiele/vod2pod-rss/assets/92220901/c5811861-6ace-41ca-9551-d7a100021c68">

**Comment by davnozdu** [comment]
Yes, stack it is started, i am stop and start stack again and witout result

**Comment by davnozdu** [comment]
I check manualy 80 port and all start to work.
Thanks 
<img width="1164" alt="Снимок экрана 2024-05-12 в 10 39 19" src="https://github.com/madiele/vod2pod-rss/assets/92220901/fd2a9e40-cd74-4272-8b2e-2f60f83b30f2">

**Comment by madiele** [comment]
Try to remove the api_keys section in the editor and redeploy, maybe portainer does not like the syntax. If it works you can add the environment variables directly in the vod2pod section

**Comment by madiele** [comment]
Oh cool! Glad you fixed it ✌️

**Comment by madiele** [comment]
BTW you can remove the standalone redis container if you don't use it for other things
