### ISSUE TITLE
Error interacting with Redis on Docker Desktop

### ISSUE THREAD

**Issue by yakamatt** [madiele/vod2pod-rss#208]
app version: 2.7.0
Docker Desktop on Mac bookair M2
Last Redis version running
______
issue description:
Hi, (big noob here, not a coder !!)
First move on Docker and trying to run Vod2pod...
Redis container is running, but I have this issue...
Any idea ??
Thanks a lot Matt

<your issue here be sure to include logs if you can>
2024-08-30 19:47:33 2024-08-30T17:47:33.636Z INFO  [app] app version 1.2.2
2024-08-30 19:47:33 thread 'main' panicked at src/main.rs:22:9:
2024-08-30 19:47:33 Error interacting with Redis (redis is required): Connection refused (os error 111)
2024-08-30 19:47:33 
2024-08-30 19:47:33 Location:
2024-08-30 19:47:33     /tmp/vod2pod/src/lib.rs:13:15
2024-08-30 19:47:33 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by madiele** [comment]
Hi can you share your docker compose file and the commands you used to stars vod2pod-rss?

**Comment by yakamatt** [comment]
Here is what I found : Compose file (docker-compose.yml)
`sudo docker compose up -d`

I run the container via the play button
(really noob here ;-)

**Comment by madiele** [comment]
Can you paste the content of the docker-compose.yml? (obscure any api key of course)

**Comment by madiele** [comment]
Oh wait, you said you run the container with the play button, that is your problem, by running it manually you are not running the redis container.

Please check if docker desktop has a section to use docker compose files in, and use that, do not manually start just the vod2pod container with the play button

**Comment by madiele** [comment]
I'll close the issues due to inactivity, if the given solution does not work feel free to ask me to reopen it

**Comment by yakamatt** [comment]
I wasn't at home this week. I'll check this this week-end 😅

**Comment by madiele** [comment]
> I wasn't at home this week. I'll check this this week-end 😅

No worry, I'll reopen then, let me know ✌️

**Comment by yakamatt** [comment]
I've tried many things ... I think it's not for newbies (yet)...
Unless a detailed tutorial from scratch, I think I have to forget about this...
Very sad, your tool seems PERFECT for my need :-)
You can close the ticket :-)
Thanks for your time. Matt

**Comment by madiele** [comment]
If you want to try again I suggest you try from scratch using only terminal + docker + docker compose. You don't need any interface like portainer or docker desktop as this project is pretty light on setup, go to Bing copilot and ask it on how to use docker compose from terminal to run vod2pod-rss (give it the link to the repo so it scans the Readme).

It's not as hard as it sounds, if you ever feel like it, try it again like this and let me know if you make it ✌️

I could make a simple windows .exe to run too but I don't want people to get confused as this is not a desktop application and it's meant to be always running on a computer you can reach from the network

**Comment by yakamatt** [comment]
I FINALLY MADE IT !!!! A friend of mine suggested me to use chatgpt ... "just explain to me how to use this script on a mac" ... and it was PERFECT !!
Now I use your script. Work well for Youtube but have a "409 error" trying to generate flux on any twitch channel (haven't put any api key so far).
Any idea about 409 ??

**Comment by madiele** [comment]
Great to hear! 😊

As for the 409 twitch support only works with a twitch API key

**Comment by yakamatt** [comment]
IT'S ALIIIIIIIIVE !!!! thanks to chatgpt again, I just downloaded my 1st podcast ep. with VOD2POD on my phone !! Thanks a lot man !!!! really great job !!!
