### ISSUE TITLE
Transcoding does not stop after stopping the player

### ISSUE THREAD

**Issue by acamposcar** [madiele/vod2pod-rss#222]
app version: 1.2.3 beta

- [ ] twitch api key set
- [X] youtube api key set

______

Hi there. I've seen that when transcoding an episode starts, it doesn't stop when the player is closed. I've tested this using the audio player in Chrome and I've seen the ffmpeg process keeps running (and using CPU) even when I close Chrome.

Any idea?

Love the project! Good work!

Thanks!

**Comment by madiele** [comment]
I theory it should stop as soon as the connection to the server is dropped, I remember I did verified it, does it happens also if you close chrome? Are you hitting the stop button on the ui? Or just pause?

The stop button shoud stop the transcoding, the pause does not as chrome will keep buffering

**Comment by acamposcar** [comment]
It was an error with my server configuration. Now it is working fine again!
