### ISSUE TITLE
Adjust Update Interval?

### ISSUE THREAD

**Issue by jcoz00** [madiele/vod2pod-rss#232]
app version: 1.2.3-beta-cfed0af

- [ ] twitch api key set
- [X ] youtube api key set

______
issue description:

With Apple Podcasts, it seems I often need to manually refresh the subscribed podcasts to get the most up-to-date videos. Is there a way to adjust the auto-update interval to push the latest videos more frequently?

Thank you!!

**Comment by madiele** [comment]
Vod2pod-rss has no control on that, it's a choice on apple podcast to only refresh the feed sporadically, I would check the settings if there is something about it.

Vod2pod-rss does cache requests in the span of 10 minutes, but other than that you can call it and receive the latest videos no problem
