### ISSUE TITLE
how to use at openwrt docker compose

### ISSUE THREAD

**Issue by Yumega** [madiele/vod2pod-rss#81]
app version: X.X.X

- [ ] twitch api key set
- [x] youtube api key set

______
issue description:
in docker-compose.yml 
# Set your YouTube API key
      - YT_API_KEY=AIzaSyDDzD9kXXXXXXX 
is this right？ 
<your issue here be sure to include logs if you can>

**Comment by madiele** [comment]
You will have to find the architecture of this machine, at the moment only arm64, amd64 and armv7 are supported.

**Comment by Yumega** [comment]
> You will have to find the architecture of this machine, at the moment only arm64, amd64 and armv7 are supported.

my machine is x86
I have successful lauched the page now, but it can't generate RSS,  the  container  name vod2pod-api_keys-1 auto exit. 
 
I set my key like this  
      YT_API_KEY=AIzaSyDDzD2kidMo_KgNot1DB93eYR08jwFE2  like this not the real one

**Comment by Yumega** [comment]
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/72a3612c-db09-41b1-81e6-c904e26af4dd)

**Comment by madiele** [comment]
vod2pod-api_keys-1 auto-exiting is normal, and the API key looks good (you can even leave it blank for now, it works even without it, slower but it works, at least you have less things to worry about for now).

can you share your logs for the vod2pod container? Also set RUST_LOG to `DEBUG`

I did not made any x86 image though, so I don't know how you got it to launch without a `docker compose build`

**Comment by Yumega** [comment]
stdout: 2023-06-25T20:57:14.749Z INFO  [app] app version 1.0.2
stdout: 2023-06-25T20:57:14.751Z INFO  [app] starting server at http://0.0.0.0:8080
stdout: 2023-06-25T20:57:14.751Z INFO  [actix_server::builder] starting 4 workers
stdout: 2023-06-25T20:57:14.751Z INFO  [actix_server::server] Actix runtime found; starting in Actix runtime
stdout: 2023-06-25T20:57:36.229Z INFO  [app] serving homepage - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36, Remote Address: 192.168.11.212, Referer: http://192.168.11.1/

page lanuched 
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/994393c3-4811-4674-8a94-10e46167c416)


OpenWRT
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/3b0e2a49-6b84-4289-a5c6-3022c3cfc50d)

**Comment by madiele** [comment]
Seems all good to me, what happens when you try to generate something?

If you give it this link

https://youtube.com/@LinusTechTips

Does it work?

**Comment by Yumega** [comment]
wow, the problem was the key, after I leave it blank , it works now. ( I don't know what's wrong with the key)
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/c102b0b2-d351-45e5-bf67-6ff0c17ce4dc)

**Comment by madiele** [comment]
Anyway, seems like it's an x86_64 also know as amd64 so that's probably why it's working, it's a supported architecture 😉

**Comment by madiele** [comment]
The key is only really needed for faster generation or if you need Playlist support, when using the key also check the podtube container for error logs

**Comment by Yumega** [comment]
I will try new key tomorrow. Thank you a lot.

**Comment by Yumega** [comment]
> The key is only really needed for faster generation or if you need Playlist support, when using the key also check the podtube container for error logs

It refuses generate RSS with my own api key

stdout: 2023-06-26T05:26:55.116Z INFO  [app] app version 1.0.2
stdout: 2023-06-26T05:26:55.117Z INFO  [app] starting server at http://0.0.0.0:8080
stdout: 2023-06-26T05:26:55.118Z INFO  [actix_server::builder] starting 4 workers
stdout: 2023-06-26T05:26:55.118Z INFO  [actix_server::server] Actix runtime found; starting in Actix runtime
stdout: 2023-06-26T05:27:07.126Z INFO  [app] serving homepage - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36, Remote Address: 192.168.11.212, Referer: http://192.168.11.1/
stdout: 2023-06-26T05:29:25.780Z INFO  [vod2pod_rss::url_convert] trying to convert youtube channel url https://www.youtube.com/@wangzhian
stdout: 2023-06-26T05:29:25.782Z INFO  [vod2pod_rss::url_convert] conversion not in cache, using yt-dlp for conversion...
stdout: 2023-06-26T05:29:28.281Z ERROR [app] could not translate rss
stdout: 2023-06-26T05:29:28.281Z ERROR [app] error sending request for url (http://podtube:15000/youtube/channel/UCBKDRq35-L8xev4O7ZqBeLg): error trying to connect: dns error: failed to lookup address information: Name or service not known

page screenshot
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/98ab736b-f039-48cd-87de-9fa54a482673)

docker-compose.yml screenshot
![image](https://github.com/madiele/vod2pod-rss/assets/61570667/2dcc8b7e-be3c-4d60-97fd-e0ce17d45a72)

**Comment by madiele** [comment]
Do you have a podetube section in your docker compose file? Is it possible that you removed it by mistake?

**Comment by Yumega** [comment]
> Do you have a podtube section in your docker compose file? Is it possible that you removed it by mistake?
> 
> ```
>     podtube: #remove this section if you don't need improved youtube support 
>      extends: api_keys 
>      image: ftawesome/podtube 
>      restart: unless-stopped 
>      environment: 
>        - YT_AUTOLOAD_NEWEST_AUDIO=False
> ```

You're right, after I add these code back, it works now, Thanks for your excellent contributions.

**Comment by madiele** [comment]
You're welcome, I'll close the issue then, if you still have some problem feel free to reopen it ✌️
Enjoy the project!
