### ISSUE TITLE
update yt-dlp

### ISSUE THREAD

**Issue by blairun** [madiele/vod2pod-rss#97]
app version: v1.0.2

- [ ] twitch api key set
- [ ] youtube api key set

______
issue description:

Can you please update yt-dlp to the latest stable?

Running `yt-dlp --version` in the vod2pod container shows it's using version 2023.03.04.   I've started getting download errors with this version:

```
ERROR [vod2pod_rss::transcoder] https://rr2---sn-nx57ynss.googlevideo.com/videoplayback?............: Server returned 403 Forbidden (access denied)
```

Running this in the vod2pod container resolves the issue for me: `yt-dlp --update-to 2023.07.06`

Thanks

**Comment by madiele** [comment]
Done, it's building right now

**Comment by madiele** [comment]
Version 1.0.3 released with new yt-dlp, I'll close this
